"use client";
import Link from "next/link";
import { useState } from "react";
import { ArrowLeft, Check, ChevronDown, SlidersHorizontal, X } from "lucide-react";
import { MobileBottomNav } from "@/components/MobileBottomNav";

const groups: [string, string[]][] = [
  ["Category", ["All Sarees (128)","Silk (28)","Cotton (21)","Georgette (18)","Chiffon (16)","Organza (12)","Tussar (10)","Banarasi (14)"]],
  ["Fabric", ["Silk (28)","Cotton (21)","Georgette (18)","Chiffon (16)","Organza (12)","Tussar (10)","Banarasi (14)"]],
  ["Work Type", ["Zari Work","Embroidery","Printed","Plain"]],
  ["Occasion", ["Wedding","Festival","Party Wear","Daily Wear","Bridal"]],
];
export default function FiltersPage(){return <main className="min-h-screen bg-[#080a09] pb-24 lg:pb-0"><div className="mx-auto min-h-screen w-full max-w-[520px] lg:max-w-[860px]"><div className="sticky top-0 z-20 border-b border-white/8 bg-[#0b0e0b]/95 px-5 py-4 backdrop-blur-xl"><div className="flex items-center justify-between"><Link href="/shop" className="rounded-full border border-white/8 p-2"><ArrowLeft size={18}/></Link><div className="text-center"><div className="text-xs text-[#f3c653]">SAREES</div><h1 className="ld-serif text-2xl">Filters</h1></div><button className="rounded-full border border-white/8 p-2" aria-label="Close"><X size={18}/></button></div></div><section className="space-y-4 p-5"><div className="flex items-center justify-between"><div className="flex items-center gap-2 text-white/65"><SlidersHorizontal size={16}/><span className="text-sm">128 pieces found</span></div><button className="text-sm text-[#f3c653]">Clear All</button></div>{groups.map(([title, options], idx)=><FilterGroup key={title} title={title} options={options} defaultOpen={idx<2}/>) }<div className="rounded-2xl border border-white/8 p-4"><div className="flex items-center justify-between"><div><div className="ld-serif text-xl">Price Range</div><div className="text-xs text-white/45">Choose your budget</div></div><div className="text-[#f3c653]">₹</div></div><div className="mt-5 h-1.5 rounded-full bg-white/10"><div className="h-full w-3/4 rounded-full bg-gradient-to-r from-[#f5d77e] to-[#d99818]"/></div><div className="mt-2 flex justify-between text-xs text-white/45"><span>₹0</span><span>₹10,000+</span></div></div><div className="rounded-2xl border border-white/8 p-4"><div className="ld-serif text-xl">Colour</div><div className="mt-3 flex gap-3">{['#ef3046','#f172a9','#b52fc9','#5b40d9','#2f80ed','#22a99c','#31bc6b','#f3c653','#fff1dd'].map(c=><span key={c} style={{background:c}} className="h-8 w-8 rounded-full border border-white/20"/>)}</div></div><div className="rounded-2xl border border-white/8 p-4"><div className="ld-serif text-xl">Boutique</div><div className="mt-3 flex items-center gap-2 rounded-xl border border-white/8 bg-white/[.02] px-3 py-3"><span className="text-white/35">⌕</span><input className="w-full bg-transparent outline-none text-sm" placeholder="Search boutiques..."/></div></div></section><div className="sticky bottom-0 border-t border-white/8 bg-[#080a09]/95 p-4 backdrop-blur-xl"><button className="ld-gold-button w-full">Apply Filters (128) →</button></div></div><MobileBottomNav active="shop"/></main>}

function FilterGroup({title, options, defaultOpen}:{title:string;options:string[];defaultOpen:boolean}){const [open,setOpen]=useState(defaultOpen);return <div className="rounded-2xl border border-white/8"><button onClick={()=>setOpen(v=>!v)} className="flex w-full items-center justify-between p-4 text-left"><div><div className="ld-serif text-xl">{title}</div><div className="text-xs text-white/45">Choose {title.toLowerCase()}</div></div><ChevronDown size={18} className={open?'rotate-180':''}/></button>{open&&<div className="grid gap-2 border-t border-white/6 p-4 sm:grid-cols-2">{options.map((o,i)=><button key={o} className={`flex items-center justify-between rounded-xl border p-3 text-sm ${i===0?'border-[#f3c653]/60 bg-[#f3c653]/8':'border-white/8 bg-white/[.02]'}`}><span>{o}</span>{i===0&&<Check size={16} className="text-[#f3c653]"/>}</button>)}</div>}</div>}
